/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificacaoRouteImport } from './routes/verificacao'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MensagensIndexRouteImport } from './routes/mensagens.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as MensagensUserIdRouteImport } from './routes/mensagens.$userId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as UNNameRouteImport } from './routes/u.n.$name'
import { Route as ApiV1PostsRouteImport } from './routes/api/v1/posts'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiV1PostsPost_idLikeRouteImport } from './routes/api/v1/posts.$post_id.like'
import { Route as ApiV1PostsPost_idCommentsRouteImport } from './routes/api/v1/posts.$post_id.comments'

const VerificacaoRoute = VerificacaoRouteImport.update({
  id: '/verificacao',
  path: '/verificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensIndexRoute = MensagensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MensagensRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensUserIdRoute = MensagensUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MensagensRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const UNNameRoute = UNNameRouteImport.update({
  id: '/u/n/$name',
  path: '/u/n/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsRoute = ApiV1PostsRouteImport.update({
  id: '/api/v1/posts',
  path: '/api/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1PostsPost_idLikeRoute = ApiV1PostsPost_idLikeRouteImport.update({
  id: '/$post_id/like',
  path: '/$post_id/like',
  getParentRoute: () => ApiV1PostsRoute,
} as any)
const ApiV1PostsPost_idCommentsRoute =
  ApiV1PostsPost_idCommentsRouteImport.update({
    id: '/$post_id/comments',
    path: '/$post_id/comments',
    getParentRoute: () => ApiV1PostsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/developers': typeof DevelopersRoute
  '/equipe': typeof EquipeRoute
  '/mcp': typeof McpRoute
  '/mensagens': typeof MensagensRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verificacao': typeof VerificacaoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/mensagens/$userId': typeof MensagensUserIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$id': typeof UIdRoute
  '/mensagens/': typeof MensagensIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/u/n/$name': typeof UNNameRoute
  '/api/v1/posts/$post_id/comments': typeof ApiV1PostsPost_idCommentsRoute
  '/api/v1/posts/$post_id/like': typeof ApiV1PostsPost_idLikeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/developers': typeof DevelopersRoute
  '/equipe': typeof EquipeRoute
  '/mcp': typeof McpRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verificacao': typeof VerificacaoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/mensagens/$userId': typeof MensagensUserIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$id': typeof UIdRoute
  '/mensagens': typeof MensagensIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/u/n/$name': typeof UNNameRoute
  '/api/v1/posts/$post_id/comments': typeof ApiV1PostsPost_idCommentsRoute
  '/api/v1/posts/$post_id/like': typeof ApiV1PostsPost_idLikeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/developers': typeof DevelopersRoute
  '/equipe': typeof EquipeRoute
  '/mcp': typeof McpRoute
  '/mensagens': typeof MensagensRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verificacao': typeof VerificacaoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/mensagens/$userId': typeof MensagensUserIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$id': typeof UIdRoute
  '/mensagens/': typeof MensagensIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/u/n/$name': typeof UNNameRoute
  '/api/v1/posts/$post_id/comments': typeof ApiV1PostsPost_idCommentsRoute
  '/api/v1/posts/$post_id/like': typeof ApiV1PostsPost_idLikeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/comunidade'
    | '/developers'
    | '/equipe'
    | '/mcp'
    | '/mensagens'
    | '/perfil'
    | '/sitemap.xml'
    | '/verificacao'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/mensagens/$userId'
    | '/post/$id'
    | '/u/$id'
    | '/mensagens/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/v1/posts'
    | '/u/n/$name'
    | '/api/v1/posts/$post_id/comments'
    | '/api/v1/posts/$post_id/like'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/comunidade'
    | '/developers'
    | '/equipe'
    | '/mcp'
    | '/perfil'
    | '/sitemap.xml'
    | '/verificacao'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/mensagens/$userId'
    | '/post/$id'
    | '/u/$id'
    | '/mensagens'
    | '/.mcp/invoke-tool/$tool'
    | '/api/v1/posts'
    | '/u/n/$name'
    | '/api/v1/posts/$post_id/comments'
    | '/api/v1/posts/$post_id/like'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/comunidade'
    | '/developers'
    | '/equipe'
    | '/mcp'
    | '/mensagens'
    | '/perfil'
    | '/sitemap.xml'
    | '/verificacao'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/mensagens/$userId'
    | '/post/$id'
    | '/u/$id'
    | '/mensagens/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/v1/posts'
    | '/u/n/$name'
    | '/api/v1/posts/$post_id/comments'
    | '/api/v1/posts/$post_id/like'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DevelopersRoute: typeof DevelopersRoute
  EquipeRoute: typeof EquipeRoute
  McpRoute: typeof McpRoute
  MensagensRoute: typeof MensagensRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerificacaoRoute: typeof VerificacaoRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PostIdRoute: typeof PostIdRoute
  UIdRoute: typeof UIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiV1PostsRoute: typeof ApiV1PostsRouteWithChildren
  UNNameRoute: typeof UNNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificacao': {
      id: '/verificacao'
      path: '/verificacao'
      fullPath: '/verificacao'
      preLoaderRoute: typeof VerificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/': {
      id: '/mensagens/'
      path: '/'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof MensagensIndexRouteImport
      parentRoute: typeof MensagensRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/$userId': {
      id: '/mensagens/$userId'
      path: '/$userId'
      fullPath: '/mensagens/$userId'
      preLoaderRoute: typeof MensagensUserIdRouteImport
      parentRoute: typeof MensagensRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/n/$name': {
      id: '/u/n/$name'
      path: '/u/n/$name'
      fullPath: '/u/n/$name'
      preLoaderRoute: typeof UNNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts': {
      id: '/api/v1/posts'
      path: '/api/v1/posts'
      fullPath: '/api/v1/posts'
      preLoaderRoute: typeof ApiV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts/$post_id/like': {
      id: '/api/v1/posts/$post_id/like'
      path: '/$post_id/like'
      fullPath: '/api/v1/posts/$post_id/like'
      preLoaderRoute: typeof ApiV1PostsPost_idLikeRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/v1/posts/$post_id/comments': {
      id: '/api/v1/posts/$post_id/comments'
      path: '/$post_id/comments'
      fullPath: '/api/v1/posts/$post_id/comments'
      preLoaderRoute: typeof ApiV1PostsPost_idCommentsRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
  }
}

interface MensagensRouteChildren {
  MensagensUserIdRoute: typeof MensagensUserIdRoute
  MensagensIndexRoute: typeof MensagensIndexRoute
}

const MensagensRouteChildren: MensagensRouteChildren = {
  MensagensUserIdRoute: MensagensUserIdRoute,
  MensagensIndexRoute: MensagensIndexRoute,
}

const MensagensRouteWithChildren = MensagensRoute._addFileChildren(
  MensagensRouteChildren,
)

interface ApiV1PostsRouteChildren {
  ApiV1PostsPost_idCommentsRoute: typeof ApiV1PostsPost_idCommentsRoute
  ApiV1PostsPost_idLikeRoute: typeof ApiV1PostsPost_idLikeRoute
}

const ApiV1PostsRouteChildren: ApiV1PostsRouteChildren = {
  ApiV1PostsPost_idCommentsRoute: ApiV1PostsPost_idCommentsRoute,
  ApiV1PostsPost_idLikeRoute: ApiV1PostsPost_idLikeRoute,
}

const ApiV1PostsRouteWithChildren = ApiV1PostsRoute._addFileChildren(
  ApiV1PostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ComunidadeRoute: ComunidadeRoute,
  DevelopersRoute: DevelopersRoute,
  EquipeRoute: EquipeRoute,
  McpRoute: McpRoute,
  MensagensRoute: MensagensRouteWithChildren,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerificacaoRoute: VerificacaoRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PostIdRoute: PostIdRoute,
  UIdRoute: UIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiV1PostsRoute: ApiV1PostsRouteWithChildren,
  UNNameRoute: UNNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
